In [1]:
import numpy as np

In [2]:
v1 = np.array([20,200,20000])

In [3]:
v2 = np.divide(v1,20)

In [4]:
v2

array([   1.,   10., 1000.])

In [5]:
v3 = np.log10(v2)

In [6]:
v3

array([0., 1., 3.])

In [7]:
#聲壓為20000微巴斯卡為60分貝
np.multiply(v3,20)

array([ 0., 20., 60.])

In [8]:
a = np.power(10,1.5)

In [9]:
b = np.power(10,2.5)

In [10]:
#30分貝的聲壓是50分貝的幾倍
a/b

0.09999999999999999