In [1]:
import numpy as np

In [2]:
array1 = np.array([[10,8],[3,5]])

In [3]:
inv_array1 = np.linalg.inv(array1)

In [4]:
#計算array1的反矩陣inv_array1
inv_array1

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [5]:
#array1*inv_array1為單位矩陣
np.matmul(array1,inv_array1)

array([[1., 0.],
       [0., 1.]])

In [6]:
#array1的特徵值與特徵向量
w, v=np.linalg.eig(array1)

In [7]:
#特徵值
w

array([13.,  2.])

In [8]:
#特徵向量
v

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [9]:
#array1矩陣分解–SVD
u, s, vh = np.linalg.svd(array1)

In [10]:
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [11]:
s

array([13.94721714,  1.86417116])

In [12]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])